### ISSUE TITLE
Where and how are the APKs to be stored?

### ISSUE THREAD

**Issue by Jogogoloboy** [CMUChimpsLab/MobiPurpose#1]

**Comment by Jogogoloboy** [comment]
Hey there, I am trying to run your project but so far I've always bumped into trouble finding the apk as there is no real info on where and how to store them. Are they stored on the computer running the project or the device? If the latter, are they already installed? 

Can you tell me how you handled it during your project?

Thanks!

**Comment by haojian** [comment]
Just saw your questions. Sorry for the late response.

This tool does not contain the APK download part. We downloaded APK files separately and put them in a local directory.

We define the path to of APK directory here (line 8): 
https://github.com/CMUChimpsLab/MobiPurpose/blob/master/test_harness/runPacketCapture.py
